'use server';
/**
 * @fileOverview This file implements an AI copywriter tool for generating marketing copy for the Servicios RP landing page.
 *
 * - aiCopywriterForLandingPageContent - A function that generates marketing copy based on input parameters.
 * - AiCopywriterInput - The input type for the aiCopywriterForLandingPageContent function.
 * - AiCopywriterOutput - The return type for the aiCopywriterForLandingPageContent function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AiCopywriterInputSchema = z.object({
  contentType: z.enum(['headline', 'slogan', 'service description', 'company value'])
    .describe('The type of content to generate (e.g., headline, slogan, service description, company value).'),
  keywords: z.string()
    .describe('Keywords or phrases that should be included or related to the generated content.').optional(),
  companyFocus: z.string()
    .describe('A brief description of the company\'s main focus or business area.'),
  existingContent: z.string()
    .describe('Existing content that needs refinement or inspiration for a new version.').optional(),
});
export type AiCopywriterInput = z.infer<typeof AiCopywriterInputSchema>;

const AiCopywriterOutputSchema = z.object({
  copy: z.string().describe('The engaging marketing copy generated by the AI.'),
});
export type AiCopywriterOutput = z.infer<typeof AiCopywriterOutputSchema>;

const copywriterPrompt = ai.definePrompt({
  name: 'copywriterPrompt',
  input: { schema: AiCopywriterInputSchema },
  output: { schema: AiCopywriterOutputSchema },
  prompt: `You are an expert marketing copywriter for a construction and services company named "Servicios y Construcciones RP".
Your goal is to generate engaging and professional marketing copy for a landing page.

Company Focus: {{{companyFocus}}}

I need you to generate a {{contentType}}. ${'{{#if keywords}}'}Please incorporate these keywords: "{{{keywords}}}".${'{{/if}}'}${'{{#if existingContent}}'} Also, consider this existing content for inspiration or refinement: "{{{existingContent}}}".${'{{/if}}'}

Ensure the tone is professional, trustworthy, and highlights quality and commitment.

Generate only the copy, no conversational text.`,
});

const aiCopywriterForLandingPageContentFlow = ai.defineFlow(
  {
    name: 'aiCopywriterForLandingPageContentFlow',
    inputSchema: AiCopywriterInputSchema,
    outputSchema: AiCopywriterOutputSchema,
  },
  async (input) => {
    const { output } = await copywriterPrompt(input);
    return output!;
  }
);

export async function aiCopywriterForLandingPageContent(input: AiCopywriterInput): Promise<AiCopywriterOutput> {
  return aiCopywriterForLandingPageContentFlow(input);
}
